### ISSUE TITLE
Requires sudo on Ubuntu

### ISSUE THREAD

**Issue by bevacqua** [defunkt/gist#167]
``` shell
» gem install gist
Fetching: gist-4.2.1.gem (100%)
ERROR:  While executing gem ... (Errno::EACCES)
   Permission denied - /var/lib/gems/1.9.1
```

![perm](https://f.cloud.github.com/assets/934293/2271910/a1e77884-9eff-11e3-9e60-91ad499274bd.png)

Is there any way around this?
Thanks

**Comment by rosewd1954** [comment]
Thanks for accepting me. let me introduce my self to you,Am Mrs Delane Franco, A christian 58 years old,I have a donation to donate,Am a widow from manila phillipine, Recently my Doctor told me that I would not last for the next five months due to cancer problem. i decided to donate this fund to an organization or good person that will utilize this money the way I am going to instruct herein. Meanwhile I am not afraid of death hence I know where I am going. Whoever that Wants to serve the Lord must serve him in truth and faith, "serving him with all you have, knowing that naked we come and naked we must go" Contact me on the this email address (francodelane AT outlook.fr) and any delay in your reply will give me room in sourcing another good person, organization for this same purpose. Please assure me that you will act accordingly as I Stated herein. Remain bless in the lord. Your Sister in christ . Delane Franco
