### ISSUE TITLE
Error: source sequence is illegal/malformed utf-8

### ISSUE THREAD

**Issue by airblade** [defunkt/gist#191]
I am trying to gist a patch file of Vim's source code and I get the error in the title.

`file -a a.diff` produces `text/x-diff; charset=unknown-8bit`.

**Comment by steakknife** [comment]
It would be nice to automate the following:

1. Upload a dummy file
2. Create a gist
3. git clone (using ssh url) to a temporary dir
4. Put your binary files in there
5. Upload the git

**Comment by ryan-williams** [comment]
I wrote a script that does the steps above: [`gist-dir`](https://github.com/ryan-williams/git-helpers/blob/67619637bff47dfe5c5592703a57674d5b2fb27b/gist/gist-dir).

- uploads whole directories or specific files in a provided directory (default: `$PWD`)
- [reasonably feature-ful CLI](https://github.com/ryan-williams/git-helpers/blob/67619637bff47dfe5c5592703a57674d5b2fb27b/gist/gist_dir.py#L98)
  - I used it to upload itself to [this gist](https://gist.github.com/ryan-williams/d48c15060d76e0391b2e1a579a3a4478):
    ```bash
    gist-dir -cop gist-dir gist_dir.py octocat.png
    ```
  - [handles images](https://gist.github.com/ryan-williams/d48c15060d76e0391b2e1a579a3a4478#file-octocat-png) (binary data)!
- if directory is already a git repository, pushes `HEAD` to a newly-created gist, in existing git repos
- otherwise: pushes directory contents to a newly-created gist
- operates in-place by adding the newly-created gist as a remote (instead of `git clone`ing)

hth!
