### ISSUE TITLE
It's written in Ruby

### ISSUE THREAD

**Issue by xnil** [defunkt/gist#193]
Why is this written in Ruby? I don't want to install the runtime on my computer. Can't it be done in Bash?

**Comment by mikelking** [comment]
Ha! @xnil I know the feeling... perhaps we can do something constructive about that...

**Comment by ConradIrwin** [comment]
@xnil It's in ruby because that's the language I was working in when I wrote it. I'd be very open to linking to a functionally equivalent shell-script or even a compliled binary (perhaps written in Go, Rust, or C for portability) from the README; but first we need someone with a bit of spare time on their hands (i.e. not me) to write it.
